### ISSUE TITLE
Switch from hittchip to another data set

### ISSUE THREAD

**Issue by antagomir** [microbiome/benchmarking#12]
Identify another data to use instead of hitchip1006, and replace. If suitable data is not found, perhaps we can remove hitchip1006 from the data set list. 

Ideally all data sets have `rowTree` so that phylogeny aware methods can be includede in the tests.

All data sets should have N>10000 samples.

**Comment by RiboRings** [comment]
As reported in [this list](https://waldronlab.io/curatedMetagenomicData/articles/articles/available-studies.html), the following data sets contain more than 1000 samples:
* AsnicarF_2021 (1098)
* HMP_2019_ibdmdb (1628)
* LifeLinesDeep_2016 (1135)
* ShaoY_2019 (1644)

For the moment, I am going to replace hitchip1006 with AsnicarF_2021. Potentially, we can expand the experiment to more than 3 data sets.

**Comment by antagomir** [comment]
AsnicarF is ok for now. All of these have the tree as well?

**Comment by RiboRings** [comment]
Yes, they all contain a rowTree.
