### ISSUE TITLE
Fix beta diversity estimation for GrieneisenTSData

### ISSUE THREAD

**Issue by RiboRings** [microbiome/benchmarking#14]
`experiment_benchmark(containers, datasetlist, beta_tse_exec_time, beta_pseq_exec_time, sample_sizes)` throws the error `cmdscale(.) : NA values not allowed in 'd'`.

As discussed in [this issue](https://github.com/tidymodels/corrr/issues/78), the solution is to omit or substitute NA values with zeros. 

However, the otu tables of the pseq objects derived from the tse objects do not include any NAs, so this is confising.

**Comment by antagomir** [comment]
I thought that the NAs are not in tse or pseq but instead in the dissimilarity matrix of beta diversity. The latter is calculated from tse/pseq abundance tables and if those tables contain zero rows/cols, this can lead to NAs in dissimilarity matrices. 

Do you have examples (as RData file) where tse has NAs but corresponding pseq derived from it does not?

**Comment by antagomir** [comment]
Related to [OMA#112](https://github.com/microbiome/OMA/pull/112)

**Comment by RiboRings** [comment]
Thank you, your last PR has likely fixed the issue.
