### ISSUE TITLE
New test option

### ISSUE THREAD

**Issue by antagomir** [microbiome/benchmarking#9]
When time allows it might be useful to add one more option in addition to tse and pseq, namely [speedyseq](https://mikemc.github.io/speedyseq).

The priority now is, however, in adding the other tests on alpha, beta etc. first.

**Comment by RiboRings** [comment]
Ok! I implemented the other four experiments in [this branch](https://github.com/microbiome/benchmarking/tree/RiboRings). Transformation, agglomeration and alpha diversity estimation could be smoothly added to the workflow. Beta diversity estimation required some debugging and it seems to throw an error every now and then.

**Comment by antagomir** [comment]
Closed by #20
